stages:
  online_fa:
    cmd: python experiments/online_fa.py
      --results-output-path experiments/data/online_fa_results.parquet
    deps:
      - experiments/online_fa.py
      - swafa/fa.py
      - experiments/utils/factory.py
      - experiments/utils/metrics.py
    params:
      - online_fa.gradient_optimiser
      - online_fa.gradient_optimiser_kwargs
      - online_fa.gradient_warm_up_time_steps
      - online_fa.em_warm_up_time_steps
      - online_fa.experiments
      - online_fa.n_trials
      - online_fa.n_test_samples
    outs:
      - experiments/data/online_fa_results.parquet

  online_fa_analysis:
    cmd: python experiments/online_fa_analysis.py
      --results-input-path experiments/data/online_fa_results.parquet
      --analysis-output-dir experiments/data/online_fa_analysis
    deps:
      - experiments/online_fa_analysis.py
      - experiments/data/online_fa_results.parquet
    params:
      - online_fa_analysis.min_samples
    outs:
      - experiments/data/online_fa_analysis

  download_uci_datasets:
    cmd: python experiments/uci_datasets.py
      --boston-housing-output-path experiments/data/uci_datasets/boston_housing.parquet
      --yacht-hydrodynamics-output-path experiments/data/uci_datasets/yacht_hydrodynamics.parquet
      --concrete-strength-output-path experiments/data/uci_datasets/concrete_strength.parquet
      --energy-efficiency-output-path experiments/data/uci_datasets/energy_efficiency.parquet
    deps:
      - experiments/uci_datasets.py
    outs:
      - experiments/data/uci_datasets

  linear_regression_posterior:
    cmd: python experiments/linear_regression_posterior.py
      --boston-housing-input-path experiments/data/uci_datasets/boston_housing.parquet
      --yacht-hydrodynamics-input-path experiments/data/uci_datasets/yacht_hydrodynamics.parquet
      --concrete-strength-input-path experiments/data/uci_datasets/concrete_strength.parquet
      --energy-efficiency-input-path experiments/data/uci_datasets/energy_efficiency.parquet
      --results-output-path experiments/data/linear_regression_posterior_results.parquet
    deps:
      - experiments/linear_regression_posterior.py
      - swafa/fa.py
      - swafa/models.py
      - swafa/callbacks.py
      - swafa/posterior.py
      - experiments/utils/factory.py
      - experiments/utils/metrics.py
      - experiments/utils/callbacks.py
      - experiments/data/uci_datasets
    params:
      - linear_regression_posterior.model_optimiser
      - linear_regression_posterior.model_optimiser_kwargs
      - linear_regression_posterior.n_epochs
      - linear_regression_posterior.batch_size
      - linear_regression_posterior.gradient_optimiser
      - linear_regression_posterior.gradient_optimiser_kwargs
      - linear_regression_posterior.gradient_warm_up_time_steps
      - linear_regression_posterior.em_warm_up_time_steps
      - linear_regression_posterior.posterior_update_epoch_start
      - linear_regression_posterior.posterior_eval_epoch_frequency
      - linear_regression_posterior.precision_scaling_factor
      - linear_regression_posterior.min_latent_dim
      - linear_regression_posterior.max_latent_dim
      - linear_regression_posterior.n_trials
    outs:
      - experiments/data/linear_regression_posterior_results.parquet

  linear_models_analysis:
    cmd: python experiments/linear_regression_posterior_analysis.py
      --results-input-path experiments/data/linear_regression_posterior_results.parquet
      --analysis-output-dir experiments/data/linear_regression_posterior_analysis
    deps:
      - experiments/linear_regression_posterior_analysis.py
      - experiments/data/linear_regression_posterior_results.parquet
    outs:
      - experiments/data/linear_regression_posterior_analysis
