stages:
  online_fa:
    cmd: python experiments/online_fa.py
      --results-output-path experiments/data/online_fa_results.parquet
    deps:
      - experiments/online_fa.py
      - swafa/fa.py
      - experiments/utils/factory.py
      - experiments/utils/metrics.py
    params:
      - online_fa.init_factors_noise_std
      - online_fa.gradient_optimiser
      - online_fa.gradient_optimiser_kwargs
      - online_fa.gradient_warm_up_time_steps
      - online_fa.em_warm_up_time_steps
      - online_fa.experiments
      - online_fa.n_trials
      - online_fa.n_test_samples
    outs:
      - experiments/data/online_fa_results.parquet

  online_fa_analysis:
    cmd: python experiments/online_fa_analysis.py
      --results-input-path experiments/data/online_fa_results.parquet
      --analysis-output-dir experiments/data/online_fa_analysis
    deps:
      - experiments/online_fa_analysis.py
      - experiments/data/online_fa_results.parquet
    params:
      - online_fa_analysis.min_samples
    outs:
      - experiments/data/online_fa_analysis

  download_uci_datasets:
    cmd: python experiments/uci_datasets.py
      --boston-housing-output-path experiments/data/uci_datasets/boston_housing.parquet
      --yacht-hydrodynamics-output-path experiments/data/uci_datasets/yacht_hydrodynamics.parquet
      --concrete-strength-output-path experiments/data/uci_datasets/concrete_strength.parquet
      --energy-efficiency-output-path experiments/data/uci_datasets/energy_efficiency.parquet
    deps:
      - experiments/uci_datasets.py
    outs:
      - experiments/data/uci_datasets

  linear_models:
    cmd: python experiments/linear_models.py
      --boston-housing-input-path experiments/data/uci_datasets/boston_housing.parquet
      --yacht-hydrodynamics-input-path experiments/data/uci_datasets/yacht_hydrodynamics.parquet
      --concrete-strength-input-path experiments/data/uci_datasets/concrete_strength.parquet
      --energy-efficiency-input-path experiments/data/uci_datasets/energy_efficiency.parquet
      --results-output-path experiments/data/linear_models_results.parquet
    deps:
      - experiments/linear_models.py
      - swafa/fa.py
      - swafa/models.py
      - swafa/callbacks.py
      - swafa/posterior.py
      - experiments/utils/factory.py
      - experiments/utils/metrics.py
      - experiments/utils/callbacks.py
      - experiments/data/uci_datasets
    params:
      - linear_models.model_optimiser
      - linear_models.model_optimiser_kwargs
      - linear_models.n_epochs
      - linear_models.batch_size
      - linear_models.init_factors_noise_std
      - linear_models.gradient_optimiser
      - linear_models.gradient_optimiser_kwargs
      - linear_models.gradient_warm_up_time_steps
      - linear_models.em_warm_up_time_steps
      - linear_models.posterior_update_epoch_start
      - linear_models.posterior_eval_epoch_frequency
      - linear_models.n_trials
    outs:
      - experiments/data/linear_models_results.parquet
