stages:
  online_fa:
    cmd: python experiments/online_fa.py
      --results-output-path experiments/data/online_fa_results.parquet
    deps:
      - experiments/online_fa.py
      - swafa/fa.py
    params:
      - online_fa.init_factors_noise_std
      - online_fa.gradient_optimiser_kwargs
      - online_fa.experiments
      - online_fa.n_trials
    outs:
      - experiments/data/online_fa_results.parquet

  online_fa_analysis:
    cmd: python experiments/online_fa_analysis.py
      --results-input-path experiments/data/online_fa_results.parquet
      --analysis-output-dir experiments/data/online_fa_analysis
    deps:
      - experiments/online_fa_analysis.py
      - experiments/data/online_fa_results.parquet
    outs:
      - experiments/data/online_fa_analysis
