online_fa:
  gradient_optimiser: 'sgd'
  gradient_optimiser_kwargs:
    lr: 0.001
  gradient_warm_up_time_steps: 100
  em_warm_up_time_steps: 100
  experiments:
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 1000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 1000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
  n_trials: 10

online_fa_analysis:
  min_samples: 100

linear_regression_vi:
  testing: false
  datasets:
    boston_housing:
      latent_dim: 6
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.001
      factors_optimiser_kwargs:
        lr: 0.001
      noise_optimiser_kwargs:
        lr: 0.001
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000
    yacht_hydrodynamics:
      latent_dim: 3
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 30000
    concrete_strength:
      latent_dim: 4
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000
    energy_efficiency:
      latent_dim: 4
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000
