online_fa:
  init_factors_noise_std: 0.1
  gradient_optimiser_kwargs:
    lr: 0.001
  experiments:
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 100}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 200}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 500}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 1000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 2000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 5000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 10000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 20000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 50000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [0, 1], n_samples: 100000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 100}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 200}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 500}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 1000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 2000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 5000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 10000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 20000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 50000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [0, 1], n_samples: 100000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 100}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 200}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 500}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 1000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 2000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 5000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 10000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 20000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 50000}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: 100000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 100}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 200}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 500}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 1000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 2000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 5000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 10000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 20000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 50000}
    - {observation_dim: 1000, latent_dim: 100, spectrum_range: [1, 10], n_samples: 100000}
  n_trials: 10

online_fa_analysis:
  metric_columns: ['covar_norm', 'covar_distance_sklearn', 'covar_distance_online_gradient', 'covar_distance_online_em']
