online_fa:
  gradient_optimiser: 'sgd'
  gradient_optimiser_kwargs:
    lr: 0.001
  gradient_warm_up_time_steps: 100
  em_warm_up_time_steps: 100
  experiments:
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 1000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 1000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
  n_trials: 10

online_fa_analysis:
  min_samples: 100

linear_regression_vi:
  testing: false
  datasets:
    boston_housing:
      latent_dim: 6
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.001
      factors_optimiser_kwargs:
        lr: 0.001
      noise_optimiser_kwargs:
        lr: 0.001
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000
    yacht_hydrodynamics:
      latent_dim: 3
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 30000
    concrete_strength:
      latent_dim: 4
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000
    energy_efficiency:
      latent_dim: 4
      n_gradients_per_update: 10
      optimiser: 'sgd'
      bias_optimiser_kwargs:
        lr: 0.01
      factors_optimiser_kwargs:
        lr: 0.01
      noise_optimiser_kwargs:
        lr: 0.01
      max_grad_norm: 10
      batch_size: 100
      n_epochs: 20000

neural_net_predictions:
  n_cv_folds: 5 # same as https://arxiv.org/pdf/1811.04504.pdf
  n_hyperparameter_trials: 30 # same as https://arxiv.org/pdf/1811.04504.pdf
  hidden_dims: [50] # same as https://arxiv.org/pdf/1811.04504.pdf
  hidden_activation_fn: 'relu' # same as https://arxiv.org/pdf/1811.04504.pdf
  data_split_random_seed: 1 # same as https://github.com/yaringal/DropoutUncertaintyExps/tree/master/UCI_Datasets
  test: false
  n_train_test_splits: 20 # same as https://arxiv.org/pdf/1811.04504.pdf
  train_fraction: 0.9  # same as https://arxiv.org/pdf/1811.04504.pdf
  datasets: # same as https://github.com/aaronpmishkin/SLANG/tree/master/code/python/libs/vi_lib/experiments/uci
    boston_housing:
      latent_dim: 1
      n_gradients_per_update: 4
      max_grad_norm: null
      batch_size: 10
      n_epochs: 120
      learning_rate_range: [0.001, 0.05] #[0.01, 0.02]
      prior_precision_range: [0.01, 10] #[5, 10] #[0.1353, 7.3891]
      noise_precision_range: [0.01, 1] #[0.05, 0.2] #[0.0742, 0.1108]
      n_bma_samples: 10
    yacht_hydrodynamics:
      latent_dim: 1
      n_gradients_per_update: 4
      max_grad_norm: null
      batch_size: 10
      n_epochs: 120
      learning_rate_range: [0.001, 0.05] #[0.01, 0.02]
      prior_precision_range: [0.01, 10]  #[0.1, 10] #[0.1353, 7.3891]
      noise_precision_range: [0.01, 1] #[0.1, 1] #[0.2018, 0.5488]
      n_bma_samples: 10
    concrete_strength:
      latent_dim: 1
      n_gradients_per_update: 4
      max_grad_norm: null
      batch_size: 10
      n_epochs: 120
      learning_rate_range: [0.001, 0.05] #[0.01, 0.02]
      prior_precision_range: [0.01, 10]  #[5, 10] #[0.1353, 7.3891]
      noise_precision_range: [0.01, 1] #[0.0247, 0.0672]
      n_bma_samples: 10
    energy_efficiency:
      latent_dim: 1
      n_gradients_per_update: 4
      max_grad_norm: null
      batch_size: 10
      n_epochs: 120
      learning_rate_range: [0.001, 0.05] #[0.001, 0.02]
      prior_precision_range: [0.01, 10]  #[0.0183, 1.0]
      noise_precision_range: [0.01, 1] #[0.7408, 1.105]
      n_bma_samples: 10
