online_fa:
  gradient_optimiser: 'sgd'
  gradient_optimiser_kwargs:
    lr: 0.001
  gradient_warm_up_time_steps: 100
  em_warm_up_time_steps: 100
  experiments:
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 100, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 100], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
    - {observation_dim: 1000, latent_dim: 10, spectrum_range: [1, 10000], n_samples: [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]}
  n_trials: 10
  n_test_samples: 100000

online_fa_analysis:
  min_samples: 100

linear_models:
  model_optimiser: 'sgd'
  model_optimiser_kwargs:
    lr: 0.001
  n_epochs: 500
  batch_size: 32
  gradient_optimiser: 'sgd'
  gradient_optimiser_kwargs:
    lr: 0.001
  gradient_warm_up_time_steps: 100
  em_warm_up_time_steps: 100
  posterior_update_epoch_start: 10
  posterior_eval_epoch_frequency: 10
  precision_scaling_factor: 0.1
  n_trials: 10
